# Generated by Django 4.1.1 on 2022-09-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Country name')),
                ('city', models.CharField(max_length=255, verbose_name='City name')),
                ('lat', models.DecimalField(blank=True, decimal_places=2, max_digits=255, verbose_name='Geographical coordinates latitude')),
                ('lon', models.DecimalField(blank=True, decimal_places=2, max_digits=255, verbose_name='Geographical coordinates longitude)')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_str', models.CharField(max_length=255)),
                ('wdir', models.DecimalField(decimal_places=2, max_digits=255)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=255)),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=255)),
                ('visibility', models.DecimalField(decimal_places=2, max_digits=255)),
                ('wspd', models.DecimalField(decimal_places=2, max_digits=255)),
                ('solarenergy', models.DecimalField(decimal_places=2, max_digits=255)),
                ('cloudcover', models.DecimalField(decimal_places=2, max_digits=255)),
                ('mint', models.DecimalField(decimal_places=2, max_digits=255)),
                ('datetime', models.IntegerField()),
                ('precip', models.IntegerField()),
                ('sealevelpressure', models.DecimalField(decimal_places=2, max_digits=255)),
                ('snow', models.IntegerField()),
                ('dew', models.DecimalField(decimal_places=2, max_digits=255)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=255)),
                ('precipcover', models.IntegerField()),
                ('wgust', models.DecimalField(decimal_places=2, max_digits=255)),
                ('conditions', models.CharField(max_length=255)),
            ],
        ),
    ]
