# Generated by Django 4.1.1 on 2022-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregation', '0002_remove_weatherdata_datetime_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='datetime',
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
    ]
